---
book_repo: docs-book
layout_repo: docs-layout

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

pcf_header: &local_pcf
  use_local_header: true
  latest_stable_version: 1.7
  changelog_href: http://docs.pivotal.io/scheduler/1-3/release-notes.html
  local_header_img: /images/cloud_rings.png
  local_header_title: Pivotal Cloud Foundry
public_host: hello

sections:
  - repository:
      name: docs-content
    directory: scheduler-for-pcf
    subnav_template: scheduler-for-pcf_subnav.erb

template_variables:                             # optional

book_title: Scheduler
book_repo: docs-book
layout_repo: docs-layout
